# Generated by Django 4.1.6 on 2023-02-13 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ramo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(choices=[('constr', 'Construção'), ('auto', 'Automobilistica'), ('Fer', 'Ferrovia')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razãoSocial', models.CharField(max_length=30)),
                ('nomeFantasia', models.CharField(max_length=30)),
                ('cnpj', models.CharField(max_length=14)),
                ('ramo', models.CharField(max_length=20)),
                ('representante', models.CharField(max_length=30)),
                ('fone01', models.CharField(max_length=11)),
                ('fone02', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=30)),
                ('número', models.IntegerField(max_length=5)),
                ('rua', models.CharField(max_length=40)),
                ('cidade', models.CharField(max_length=40)),
                ('estado', models.CharField(max_length=40)),
                ('cep', models.CharField(max_length=8)),
                ('categoria', models.ForeignKey(choices=[('constr', 'Construção'), ('auto', 'Automobilistica'), ('Fer', 'Ferrovia')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.ramo')),
            ],
        ),
    ]
