# Generated by Django 4.1.6 on 2023-02-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='número',
            field=models.IntegerField(),
        ),
    ]
